### ISSUE TITLE
Need to type trailing spaces

### ISSUE THREAD

**Issue by 770grappenmaker** [togglebyte/toggle_cool_cow_says_type#17]
This was tested on Windows. When I have to write a sentence, I also need to typing trailing spaces. This seems like a bug, and I can't see the space.

Environment: Win10, Shell: CMD

**Comment by 770grappenmaker** [comment]
Hmm, this issue is invalid, as it seems to be a feature when you make an error halfway, you need to confirm with a space.

**Comment by hardliner66** [comment]
The trailing space is always needed if you have an error somewhere. As a confirmation that you don't want to go back and fix it.

This is how monkeytype does it.
