### ISSUE TITLE
Crashes when run over SSH or in Docker

### ISSUE THREAD

**Issue by dnaka91** [togglebyte/toggle_cool_cow_says_type#18]
When running `tccst` remotely over SSH it can't get the terminal size and crashes.
```sh
ssh server ./tccst code
```
Assuming the program is placed on `server` in the home folder and with a folder `code` containing source code to read. 

When running inside a Docker container it doesn't crash but always gets a width and height of `0`, exiting with a wrong error that says it couldn't find any source code to read. 
```sh
docker run --rm -it -v $PWD:/volume tccst
```
Assuming the program is put in a Docker image with `/volume` set as workspace folder and `$PWD` being some code project with Rust source code.

**Comment by togglebyte** [comment]
Todo: verify that term size works in Docker when using SSH

Update: tested by Dnaka and should work

**Comment by dnaka91** [comment]
So it works for Docker just fine but doesn't with SSH. It works already now by the typical workflow of first logging in via SSH and then running firstly on the machine.

Only if using the run-and-exit style for SSH (like in the issue description) it doesn't work. But this may just be an extra ssh option that's just missing.

Mostly I'm interested in the docker support (wanted to add a Dockerfile to the repo but then stumbled upon this). Did the SSH part only out of curiosity.

**Comment by togglebyte** [comment]
> Only if using the run-and-exit style for SSH (like in the issue description) it doesn't work. But this may just be an extra ssh option that's just missing.

Does this mean that crossterm shows the correct size is you do run-and-exit style ssh?

**Comment by dnaka91** [comment]
No this is the only situation where it doesn't work and you get an error back. You can't even get anything back from the `event` function as it always fails in this case.

**Comment by togglebyte** [comment]
Are you happy for me to close this with a wont-fix tag, as it seems to be an issue outside of this project?

**Comment by dnaka91** [comment]
Yeah sure. Just opened this as it would have been nice to provide a Docker image as well.

But I guess most people just install it locally anyways as there is no config file or any extensive setup coming with it.
