### ISSUE TITLE
Modfiy default colors to more distinct

### ISSUE THREAD

**Issue by BarePotato** [togglebyte/toggle_cool_cow_says_type#24]
Using the default color scheme in alacritty the current color scheme was hard to differentiate between dark grey, grey, and white
perhaps pick a more muted color for the bg cursor and a more distinct fg cursor color that will survive between common terminals

maybe consider 24bit color as default as well to get around relying on a terminals color settings.

**Comment by togglebyte** [comment]
Updated cursor colour. Blue on black
